### ISSUE TITLE
??

### ISSUE THREAD

**Issue by majovec** [NLOGPlugins/NLOGMultiProtocol#1]
Its work 1.1.x players connect on 1.2 server ?

**Comment by nnnlog** [comment]
I can't sure it works. If I have a chance to test, I'll test it.

I'm so busy...

**Comment by nnnlog** [comment]
I test. 1.1's packet and 1.2's packet are different. 1.1.x players can't connect on 1.2 server.

**Comment by debil9877654321** [comment]
Create packet translator for both clients and it will work I think.
